/**
 * File I/O helpers for reports and generated assets.
 */
import fs from "node:fs";
import path from "node:path";

// ---------------------------------------------------------------------------
// File output
// ---------------------------------------------------------------------------

export function saveFile(content: string, ...segments: string[]): string {
  const filepath = path.join("digests", ...segments);
  fs.mkdirSync(path.dirname(filepath), { recursive: true });
  fs.writeFileSync(filepath, content, "utf-8");
  return filepath;
}

export function autoGenFooter(lang: "zh" | "en" = "zh"): string {
  const digestRepo = process.env["DIGEST_REPO"] ?? "";
  if (!digestRepo) return "";
  return lang === "en"
    ? `\n\n---\n*This digest is auto-generated by [agents-radar](https://github.com/${digestRepo}).*`
    : `\n\n---\n*本日报由 [agents-radar](https://github.com/${digestRepo}) 自动生成。*`;
}
